<a href="https://colab.research.google.com/github/SarthoPramanik1075/Deep-Learning/blob/main/DL_Assignment_03_Question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# DL Assignment 03

**Name:** Sartho

**Course Email:** pramaniksartho1@gmail.com


## End of Assignment

Before submitting:
- Run all cells from top to bottom.  
- Check that all answer sections are filled.  
- Instruction video অনুযায়ী আমাদের দেয়া Colab ফাইলটি থেকে প্রথম একটি Save copy in drive করে নিবা। এরপর Google colab এর মধ্যে কোডগুলো করবে এবং সেই ফাইলটি ‘Anyone with the link’ & ‘View’ Access দিয়ে ফাইলটির Shareble Link টি সাবমিট করবে।

# General Instruction

You must choose your own dataset.

The dataset must:

Be a supervised learning dataset (Regression or Binary Classification)

Contain at least 300 samples

Have at least 2 input features

Be in CSV format

You are NOT allowed to use Dataset or DataLoader.

You must implement everything manually.

# Question 01: [ Marks 05 ]

## Dataset Preparation

## Using your chosen dataset:

Load the dataset.

Perform necessary preprocessing:

Handle missing values (if any)

Encode categorical variables (if necessary)

Feature scaling (if needed)

Separate features (X) and target (y).

Convert them into NumPy arrays.

Convert them into PyTorch tensors.

Split into training and testing sets.

Clearly explain each preprocessing decision.

# **Write** Answer 01:

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('loan_data.csv') #https://www.kaggle.com/datasets/deependraverma13/lending-club-loan-data-analysis-deep-learning?resource=download
df.sample(10)

print("shape: ", df.shape)
df.describe().T.round(2)

shape:  (9578, 14)

,count,mean,std,min,25%,50%,75%,max
credit.policy,9578.0,0.80,0.40,0.00,1.00,1.00,1.00,1.00
int.rate,9578.0,0.12,0.03,0.06,0.10,0.12,0.14,0.22
installment,9578.0,319.09,207.07,15.67,163.77,268.95,432.76,940.14
log.annual.inc,9578.0,10.93,0.61,7.55,10.56,10.93,11.29,14.53
dti,9578.0,12.61,6.88,0.00,7.21,12.66,17.95,29.96
fico,9578.0,710.85,37.97,612.00,682.00,707.00,737.00,827.00
days.with.cr.line,9578.0,4560.77,2496.93,178.96,2820.00,4139.96,5730.00,17639.96
revol.bal,9578.0,16913.96,33756.19,0.00,3187.00,8596.00,18249.50,1207359.00
revol.util,9578.0,46.80,29.01,0.00,22.60,46.30,70.90,119.00
inq.last.6mths,9578.0,1.58,2.20,0.00,0.00,1.00,2.00,33.00
delinq.2yrs,9578.0,0.16,0.55,0.00,0.00,0.00,0.00,13.00
pub.rec,9578.0,0.06,0.26,0.00,0.00,0.00,0.00,5.00
not.fully.paid,9578.0,0.16,0.37,0.00,0.00,0.00,0.00,1.00

In [3]:
df.isnull().sum()

credit.policy        0
purpose              0
int.rate             0
installment          0
log.annual.inc       0
dti                  0
fico                 0
days.with.cr.line    0
revol.bal            0
revol.util           0
inq.last.6mths       0
delinq.2yrs          0
pub.rec              0
not.fully.paid       0
dtype: int64

In [4]:
num_cols= df.select_dtypes(include='number').columns
cat_cols= df.select_dtypes(exclude='number').columns
target_cols='not.fully.paid'

print("Numerical Column: ", num_cols)
print("Catrgorical Column: ", cat_cols)
print("Target Column: ", target_cols)

Numerical Column:  Index(['credit.policy', 'int.rate', 'installment', 'log.annual.inc', 'dti',
       'fico', 'days.with.cr.line', 'revol.bal', 'revol.util',
       'inq.last.6mths', 'delinq.2yrs', 'pub.rec', 'not.fully.paid'],
      dtype='object')
Catrgorical Column:  Index(['purpose'], dtype='object')
Target Column:  not.fully.paid

In [5]:
#for one hot encoding

df = pd.get_dummies(df, columns=['purpose'], drop_first=True)

In [6]:
print(df.columns)

Index(['credit.policy', 'int.rate', 'installment', 'log.annual.inc', 'dti',
       'fico', 'days.with.cr.line', 'revol.bal', 'revol.util',
       'inq.last.6mths', 'delinq.2yrs', 'pub.rec', 'not.fully.paid',
       'purpose_credit_card', 'purpose_debt_consolidation',
       'purpose_educational', 'purpose_home_improvement',
       'purpose_major_purchase', 'purpose_small_business'],
      dtype='object')

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = df.drop(columns=[target_cols])
y = df[target_cols]

X_scaled = scaler.fit_transform(X)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Question 02: [ Marks 20 ]

## Design a neural network using nn.Module.

### The model must contain:

Input layer

At least one hidden layer

Output layer

Suitable activation function



## Justify:

Number of hidden neurons

Choice of activation function

Print  the total number of trainable parameters.

## Write Answer 02:

In [9]:
import torch
import torch.nn as nn

class LoanModel(nn.Module):
    def __init__(self, input_size):
        super(LoanModel, self).__init__()
        self.fc1 = nn.Linear(input_size, 16)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(16, 8)
        self.fc3 = nn.Linear(8, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.sigmoid(self.fc3(x))
        return x

# Question 03: [ Marks 10 ]

Choose an appropriate loss function.

Choose an optimizer.

<br>

Justify your choices based on:

Regression vs Classification

Nature of the dataset

## Write Answer 03:

In [10]:
input_size = X_train.shape[1]
model = LoanModel(input_size)

In [11]:
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# Question 04: [ Marks 15 ]

## Implement a full training loop:

Forward pass

Loss computation

Backward pass

Parameter update

Gradient reset

### Requirements:

Train for at least 100 epochs.

Print loss every 10 epochs.

Store training loss history(You can pick your own Data Structure).

Explain clearly what happens in each step of the pipeline.

## Write Answer 04:

In [12]:
import torch

# Features
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)

# Labels (important: reshape)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

In [13]:
epochs = 100

for epoch in range(epochs):
    model.train()

    # Forward pass
    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()

    # Update weights
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

Epoch [10/100], Loss: 0.6866
Epoch [20/100], Loss: 0.6632
Epoch [30/100], Loss: 0.6412
Epoch [40/100], Loss: 0.6191
Epoch [50/100], Loss: 0.5958
Epoch [60/100], Loss: 0.5710
Epoch [70/100], Loss: 0.5453
Epoch [80/100], Loss: 0.5200
Epoch [90/100], Loss: 0.4963
Epoch [100/100], Loss: 0.4753

# Question 05: [ Marks 10 ]

## Evaluate the model on test data.

## For regression:

Report MSE and MAE


## For classification:

Report Accuracy

Compare training vs testing performance.

State whether the model is underfitting or overfitting.

## Write Answer 05:

In [14]:
model.eval()

with torch.no_grad():

    test_predictions = model(X_test_tensor)
    test_predicted = (test_predictions > 0.5).float()
    test_accuracy = (test_predicted == y_test_tensor).sum().item() / len(y_test_tensor)


    train_predictions = model(X_train_tensor)
    train_predicted = (train_predictions > 0.5).float()
    train_accuracy = (train_predicted == y_train_tensor).sum().item() / len(y_train_tensor)


    print(f"Train Accuracy: {train_accuracy*100:.2f}%")
    print(f"Test Accuracy: {test_accuracy*100:.2f}%")

Train Accuracy: 83.97%
Test Accuracy: 84.08%

# Question 06: [ Marks 20 ]

## Modify at least ONE of the following:

Learning rate

Number of hidden neurons

Number of epochs

### Train again and compare:

Convergence speed

Final performance

Explain how the change affected the model.

## Write Answer 06:

In [15]:
import torch
import torch.nn as nn

class LoanModel(nn.Module):
    def __init__(self, input_size):
        super(LoanModel, self).__init__()

        # change 16 to 32
        self.fc1 = nn.Linear(input_size, 32)

        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(32, 8)
        self.fc3 = nn.Linear(8, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.sigmoid(self.fc3(x))
        return x

In [16]:

input_size = X_train.shape[1]
model = LoanModel(input_size)

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [17]:
epochs = 250 #increase epoch
for epoch in range(epochs):
    model.train()

    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

Epoch 10, Loss: 0.6610
Epoch 20, Loss: 0.6252
Epoch 30, Loss: 0.5938
Epoch 40, Loss: 0.5649
Epoch 50, Loss: 0.5373
Epoch 60, Loss: 0.5113
Epoch 70, Loss: 0.4876
Epoch 80, Loss: 0.4672
Epoch 90, Loss: 0.4506
Epoch 100, Loss: 0.4382
Epoch 110, Loss: 0.4295
Epoch 120, Loss: 0.4239
Epoch 130, Loss: 0.4204
Epoch 140, Loss: 0.4183
Epoch 150, Loss: 0.4169
Epoch 160, Loss: 0.4159
Epoch 170, Loss: 0.4151
Epoch 180, Loss: 0.4143
Epoch 190, Loss: 0.4137
Epoch 200, Loss: 0.4131
Epoch 210, Loss: 0.4125
Epoch 220, Loss: 0.4120
Epoch 230, Loss: 0.4115
Epoch 240, Loss: 0.4110
Epoch 250, Loss: 0.4106

In [18]:
model.eval()

with torch.no_grad():


    test_predictions = model(X_test_tensor)
    test_predicted = (test_predictions > 0.5).float()
    test_accuracy = (test_predicted == y_test_tensor).sum().item() / len(y_test_tensor)


    train_predictions = model(X_train_tensor)
    train_predicted = (train_predictions > 0.5).float()
    train_accuracy = (train_predicted == y_train_tensor).sum().item() / len(y_train_tensor)

    print(f"\nTrain Accuracy: {train_accuracy*100:.2f}%")
    print(f"Test Accuracy: {test_accuracy*100:.2f}%")

Train Accuracy: 83.97%
Test Accuracy: 84.08%

# Question 07: [ Marks 20 ]


# Training Analysis

Answer the following:

Why must gradients be reset every epoch?

What happens if learning rate is too high?

What happens if learning rate is too small?

Why do we define layers inside the constructor (__init__) and not inside forward()?

## Write Answer 07:

#In PyTorch, gradients do not reset automatically—they keep adding up.
#If we don’t clear them, the model will update weights using wrong values.

#If the learning rate is too high:

#i) The model takes very big steps
#ii) It may skip the correct solution
#iii) Loss may go up and down instead of decreasing

#If the learning rate is too small:

The model learns very slowly.
It takes too many epochs.
Training becomes inefficient

#We define layers in __init__ because:

They are created once.
Their weights are updated during training

#If we define them in forward():

New layers will be created every time.
The model will not learn anything