<a href="https://colab.research.google.com/github/SarthoPramanik1075/Deep-Learning/blob/main/Loan_data(DL_ass03).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

#Train Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0], test_size=.2)

In [7]:
y_train.shape

(455,)

In [8]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [9]:
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [10]:
encoder= LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test= encoder.transform(y_test)

In [11]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [12]:
len(df.columns)

31

In [13]:
len(X_train)

455

In [14]:
len(X_test)

114

In [15]:
len(y_train)

455

In [16]:
len(y_test)

114

In [17]:
len(X_train) + len(X_test)

569

In [18]:
X_train

array([[-1.49398888, -0.89658212, -1.45622344, ..., -1.02179362,
        -0.74210764, -0.50819753],
       [-0.48426744,  1.1582349 , -0.34072126, ...,  1.61340786,
         2.31065539,  6.93271897],
       [ 0.88006863, -0.51445826,  0.84851958, ...,  1.07688339,
         0.37028634, -0.12718506],
       ...,
       [-0.80280044, -1.21622033, -0.83968625, ..., -1.57670887,
        -0.23015359, -1.09200695],
       [-0.25311959, -1.3219653 , -0.26616328, ..., -0.35136602,
        -0.26491591, -0.57020982],
       [ 1.79620338,  0.39398716,  1.86447455, ...,  1.5191741 ,
         0.27389993, -0.43110116]])

In [19]:
y_train

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1])

In [20]:
y_test

array([0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0])

#Numpy Array to tensor

In [21]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

/tmp/ipykernel_7899/351712353.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_7899/351712353.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_7899/351712353.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_7899/351712353.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

##DATASET && DATALOADER

In [22]:
from torch.utils.data import Dataset, DataLoader

In [23]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features= features
    self.labels= labels
  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [24]:
train_dataset= CustomDataset(X_train_tensor, y_train_tensor)
test_dataset= CustomDataset(X_test_tensor, y_test_tensor)

In [25]:
len(train_dataset)

455

In [26]:
train_dataset[2]

(tensor([ 0.8801, -0.5145,  0.8485,  0.7554,  0.3018, -0.0081,  0.4708,  0.8873,
         -0.0104, -0.9203, -0.3474, -0.6683, -0.3292, -0.1588, -0.7808, -0.5762,
         -0.2753,  0.1240, -0.7924, -0.5232,  0.7226, -0.0772,  0.6929,  0.5766,
          0.4083, -0.0664,  0.3381,  1.0769,  0.3703, -0.1272]),
 tensor(1.))

##DataLoader

In [27]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

#Just Check

In [28]:
X_train.shape[1]

30

In [29]:
X_train.shape[0]

455

In [30]:
y_train.shape[0]

455

In [31]:
X_test.shape[1]

30

In [32]:
X_test.shape[0]

114

In [33]:
y_test.shape[0]

114

#Define Model

In [34]:
import torch.nn as nn

In [35]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid= nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [36]:
torch.rand(30,1)

tensor([[0.7404],
        [0.4244],
        [0.9150],
        [0.6452],
        [0.8515],
        [0.1341],
        [0.7251],
        [0.2692],
        [0.7609],
        [0.2117],
        [0.5628],
        [0.6528],
        [0.4211],
        [0.5803],
        [0.8720],
        [0.6602],
        [0.1749],
        [0.1178],
        [0.6096],
        [0.1950],
        [0.9183],
        [0.3442],
        [0.2586],
        [0.7537],
        [0.3832],
        [0.2189],
        [0.4419],
        [0.7235],
        [0.0601],
        [0.5047]])

In [40]:
learning_rate = 0.1
epochs = 25

In [42]:
loss_function = nn.BCELoss()

In [43]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [44]:
model = MySimpleNN(X_train_tensor.shape[1])

In [45]:
model.parameters()

#Training Pipeline

In [47]:
#Input → Prediction → Loss → Gradient → Update

model= MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
  for batch_feature, batch_labels in train_loader:
    #forward pass
    y_pred=model(batch_feature)

    #loss function
    loss= loss_function(y_pred, batch_labels.reshape(-1,1))

    #zero grad
    optimizer.zero_grad()

    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()

  print(f"{epoch+1}. Loss = {loss.item()}")

1. Loss = 0.16030395030975342
2. Loss = 0.23424364626407623
3. Loss = 0.15347878634929657
4. Loss = 0.06189974769949913
5. Loss = 0.051416438072919846
6. Loss = 0.14574487507343292
7. Loss = 0.019058244302868843
8. Loss = 0.07008986175060272
9. Loss = 0.021016882732510567
10. Loss = 0.017416823655366898
11. Loss = 0.10204519331455231
12. Loss = 0.04565059766173363
13. Loss = 0.13896943628787994
14. Loss = 0.24471643567085266
15. Loss = 0.11327766627073288
16. Loss = 0.011660809628665447
17. Loss = 0.022720875218510628
18. Loss = 0.11025585234165192
19. Loss = 0.021657796576619148
20. Loss = 0.17619238793849945
21. Loss = 0.1575055569410324
22. Loss = 0.03627956658601761
23. Loss = 0.009012030437588692
24. Loss = 0.06287019699811935
25. Loss = 0.03029431216418743

#Training Pipeline version 2

In [56]:
model = MySimpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

batch_size=32
n_sample= len(X_train_tensor)

for epoch in range(epochs):
  for start_indx in range(0, n_sample, batch_size):
    end_indx = start_indx + batch_size
    print(f"{epoch+1}.Start index {start_indx}, end index {end_indx}")
    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]

    #forward pass
    y_pred=model(X_batch)

    #loss
    loss= loss_function(y_pred, y_batch.reshape(-1,1))

    #zero grad
    optimizer.zero_grad()

    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()

  print(f"{epoch+1}. Loss = {loss.item()}")

1.Start index 0, end index 32
1.Start index 32, end index 64
1.Start index 64, end index 96
1.Start index 96, end index 128
1.Start index 128, end index 160
1.Start index 160, end index 192
1.Start index 192, end index 224
1.Start index 224, end index 256
1.Start index 256, end index 288
1.Start index 288, end index 320
1.Start index 320, end index 352
1.Start index 352, end index 384
1.Start index 384, end index 416
1.Start index 416, end index 448
1.Start index 448, end index 480
1. Loss = 0.11730791628360748
2.Start index 0, end index 32
2.Start index 32, end index 64
2.Start index 64, end index 96
2.Start index 96, end index 128
2.Start index 128, end index 160
2.Start index 160, end index 192
2.Start index 192, end index 224
2.Start index 224, end index 256
2.Start index 256, end index 288
2.Start index 288, end index 320
2.Start index 320, end index 352
2.Start index 352, end index 384
2.Start index 384, end index 416
2.Start index 416, end index 448
2.Start index 448, end index 480
2. Loss = 0.06873864680528641
3.Start index 0, end index 32
3.Start index 32, end index 64
3.Start index 64, end index 96
3.Start index 96, end index 128
3.Start index 128, end index 160
3.Start index 160, end index 192
3.Start index 192, end index 224
3.Start index 224, end index 256
3.Start index 256, end index 288
3.Start index 288, end index 320
3.Start index 320, end index 352
3.Start index 352, end index 384
3.Start index 384, end index 416
3.Start index 416, end index 448
3.Start index 448, end index 480
3. Loss = 0.04983554407954216
4.Start index 0, end index 32
4.Start index 32, end index 64
4.Start index 64, end index 96
4.Start index 96, end index 128
4.Start index 128, end index 160
4.Start index 160, end index 192
4.Start index 192, end index 224
4.Start index 224, end index 256
4.Start index 256, end index 288
4.Start index 288, end index 320
4.Start index 320, end index 352
4.Start index 352, end index 384
4.Start index 384, end index 416
4.Start index 416, end index 448
4.Start index 448, end index 480
4. Loss = 0.03939672186970711
5.Start index 0, end index 32
5.Start index 32, end index 64
5.Start index 64, end index 96
5.Start index 96, end index 128
5.Start index 128, end index 160
5.Start index 160, end index 192
5.Start index 192, end index 224
5.Start index 224, end index 256
5.Start index 256, end index 288
5.Start index 288, end index 320
5.Start index 320, end index 352
5.Start index 352, end index 384
5.Start index 384, end index 416
5.Start index 416, end index 448
5.Start index 448, end index 480
5. Loss = 0.03268624097108841
6.Start index 0, end index 32
6.Start index 32, end index 64
6.Start index 64, end index 96
6.Start index 96, end index 128
6.Start index 128, end index 160
6.Start index 160, end index 192
6.Start index 192, end index 224
6.Start index 224, end index 256
6.Start index 256, end index 288
6.Start index 288, end index 320
6.Start index 320, end index 352
6.Start index 352, end index 384
6.Start index 384, end index 416
6.Start index 416, end index 448
6.Start index 448, end index 480
6. Loss = 0.027978617697954178
7.Start index 0, end index 32
7.Start index 32, end index 64
7.Start index 64, end index 96
7.Start index 96, end index 128
7.Start index 128, end index 160
7.Start index 160, end index 192
7.Start index 192, end index 224
7.Start index 224, end index 256
7.Start index 256, end index 288
7.Start index 288, end index 320
7.Start index 320, end index 352
7.Start index 352, end index 384
7.Start index 384, end index 416
7.Start index 416, end index 448
7.Start index 448, end index 480
7. Loss = 0.024481022730469704
8.Start index 0, end index 32
8.Start index 32, end index 64
8.Start index 64, end index 96
8.Start index 96, end index 128
8.Start index 128, end index 160
8.Start index 160, end index 192
8.Start index 192, end index 224
8.Start index 224, end index 256
8.Start index 256, end index 288
8.Start index 288, end index 320
8.Start index 320, end index 352
8.Start index 352, end index 384
8.Start index 384, end index 416
8.Start index 416, end index 448
8.Start index 448, end index 480
8. Loss = 0.021774200722575188
9.Start index 0, end index 32
9.Start index 32, end index 64
9.Start index 64, end index 96
9.Start index 96, end index 128
9.Start index 128, end index 160
9.Start index 160, end index 192
9.Start index 192, end index 224
9.Start index 224, end index 256
9.Start index 256, end index 288
9.Start index 288, end index 320
9.Start index 320, end index 352
9.Start index 352, end index 384
9.Start index 384, end index 416
9.Start index 416, end index 448
9.Start index 448, end index 480
9. Loss = 0.01961427740752697
10.Start index 0, end index 32
10.Start index 32, end index 64
10.Start index 64, end index 96
10.Start index 96, end index 128
10.Start index 128, end index 160
10.Start index 160, end index 192
10.Start index 192, end index 224
10.Start index 224, end index 256
10.Start index 256, end index 288
10.Start index 288, end index 320
10.Start index 320, end index 352
10.Start index 352, end index 384
10.Start index 384, end index 416
10.Start index 416, end index 448
10.Start index 448, end index 480
10. Loss = 0.017849132418632507
11.Start index 0, end index 32
11.Start index 32, end index 64
11.Start index 64, end index 96
11.Start index 96, end index 128
11.Start index 128, end index 160
11.Start index 160, end index 192
11.Start index 192, end index 224
11.Start index 224, end index 256
11.Start index 256, end index 288
11.Start index 288, end index 320
11.Start index 320, end index 352
11.Start index 352, end index 384
11.Start index 384, end index 416
11.Start index 416, end index 448
11.Start index 448, end index 480
11. Loss = 0.01637866534292698
12.Start index 0, end index 32
12.Start index 32, end index 64
12.Start index 64, end index 96
12.Start index 96, end index 128
12.Start index 128, end index 160
12.Start index 160, end index 192
12.Start index 192, end index 224
12.Start index 224, end index 256
12.Start index 256, end index 288
12.Start index 288, end index 320
12.Start index 320, end index 352
12.Start index 352, end index 384
12.Start index 384, end index 416
12.Start index 416, end index 448
12.Start index 448, end index 480
12. Loss = 0.01513427309691906
13.Start index 0, end index 32
13.Start index 32, end index 64
13.Start index 64, end index 96
13.Start index 96, end index 128
13.Start index 128, end index 160
13.Start index 160, end index 192
13.Start index 192, end index 224
13.Start index 224, end index 256
13.Start index 256, end index 288
13.Start index 288, end index 320
13.Start index 320, end index 352
13.Start index 352, end index 384
13.Start index 384, end index 416
13.Start index 416, end index 448
13.Start index 448, end index 480
13. Loss = 0.014067143201828003
14.Start index 0, end index 32
14.Start index 32, end index 64
14.Start index 64, end index 96
14.Start index 96, end index 128
14.Start index 128, end index 160
14.Start index 160, end index 192
14.Start index 192, end index 224
14.Start index 224, end index 256
14.Start index 256, end index 288
14.Start index 288, end index 320
14.Start index 320, end index 352
14.Start index 352, end index 384
14.Start index 384, end index 416
14.Start index 416, end index 448
14.Start index 448, end index 480
14. Loss = 0.013141714967787266
15.Start index 0, end index 32
15.Start index 32, end index 64
15.Start index 64, end index 96
15.Start index 96, end index 128
15.Start index 128, end index 160
15.Start index 160, end index 192
15.Start index 192, end index 224
15.Start index 224, end index 256
15.Start index 256, end index 288
15.Start index 288, end index 320
15.Start index 320, end index 352
15.Start index 352, end index 384
15.Start index 384, end index 416
15.Start index 416, end index 448
15.Start index 448, end index 480
15. Loss = 0.012331382371485233
16.Start index 0, end index 32
16.Start index 32, end index 64
16.Start index 64, end index 96
16.Start index 96, end index 128
16.Start index 128, end index 160
16.Start index 160, end index 192
16.Start index 192, end index 224
16.Start index 224, end index 256
16.Start index 256, end index 288
16.Start index 288, end index 320
16.Start index 320, end index 352
16.Start index 352, end index 384
16.Start index 384, end index 416
16.Start index 416, end index 448
16.Start index 448, end index 480
16. Loss = 0.011615785770118237
17.Start index 0, end index 32
17.Start index 32, end index 64
17.Start index 64, end index 96
17.Start index 96, end index 128
17.Start index 128, end index 160
17.Start index 160, end index 192
17.Start index 192, end index 224
17.Start index 224, end index 256
17.Start index 256, end index 288
17.Start index 288, end index 320
17.Start index 320, end index 352
17.Start index 352, end index 384
17.Start index 384, end index 416
17.Start index 416, end index 448
17.Start index 448, end index 480
17. Loss = 0.010979180224239826
18.Start index 0, end index 32
18.Start index 32, end index 64
18.Start index 64, end index 96
18.Start index 96, end index 128
18.Start index 128, end index 160
18.Start index 160, end index 192
18.Start index 192, end index 224
18.Start index 224, end index 256
18.Start index 256, end index 288
18.Start index 288, end index 320
18.Start index 320, end index 352
18.Start index 352, end index 384
18.Start index 384, end index 416
18.Start index 416, end index 448
18.Start index 448, end index 480
18. Loss = 0.010409080423414707
19.Start index 0, end index 32
19.Start index 32, end index 64
19.Start index 64, end index 96
19.Start index 96, end index 128
19.Start index 128, end index 160
19.Start index 160, end index 192
19.Start index 192, end index 224
19.Start index 224, end index 256
19.Start index 256, end index 288
19.Start index 288, end index 320
19.Start index 320, end index 352
19.Start index 352, end index 384
19.Start index 384, end index 416
19.Start index 416, end index 448
19.Start index 448, end index 480
19. Loss = 0.00989554263651371
20.Start index 0, end index 32
20.Start index 32, end index 64
20.Start index 64, end index 96
20.Start index 96, end index 128
20.Start index 128, end index 160
20.Start index 160, end index 192
20.Start index 192, end index 224
20.Start index 224, end index 256
20.Start index 256, end index 288
20.Start index 288, end index 320
20.Start index 320, end index 352
20.Start index 352, end index 384
20.Start index 384, end index 416
20.Start index 416, end index 448
20.Start index 448, end index 480
20. Loss = 0.009430521167814732
21.Start index 0, end index 32
21.Start index 32, end index 64
21.Start index 64, end index 96
21.Start index 96, end index 128
21.Start index 128, end index 160
21.Start index 160, end index 192
21.Start index 192, end index 224
21.Start index 224, end index 256
21.Start index 256, end index 288
21.Start index 288, end index 320
21.Start index 320, end index 352
21.Start index 352, end index 384
21.Start index 384, end index 416
21.Start index 416, end index 448
21.Start index 448, end index 480
21. Loss = 0.009007412008941174
22.Start index 0, end index 32
22.Start index 32, end index 64
22.Start index 64, end index 96
22.Start index 96, end index 128
22.Start index 128, end index 160
22.Start index 160, end index 192
22.Start index 192, end index 224
22.Start index 224, end index 256
22.Start index 256, end index 288
22.Start index 288, end index 320
22.Start index 320, end index 352
22.Start index 352, end index 384
22.Start index 384, end index 416
22.Start index 416, end index 448
22.Start index 448, end index 480
22. Loss = 0.008620768785476685
23.Start index 0, end index 32
23.Start index 32, end index 64
23.Start index 64, end index 96
23.Start index 96, end index 128
23.Start index 128, end index 160
23.Start index 160, end index 192
23.Start index 192, end index 224
23.Start index 224, end index 256
23.Start index 256, end index 288
23.Start index 288, end index 320
23.Start index 320, end index 352
23.Start index 352, end index 384
23.Start index 384, end index 416
23.Start index 416, end index 448
23.Start index 448, end index 480
23. Loss = 0.008266049437224865
24.Start index 0, end index 32
24.Start index 32, end index 64
24.Start index 64, end index 96
24.Start index 96, end index 128
24.Start index 128, end index 160
24.Start index 160, end index 192
24.Start index 192, end index 224
24.Start index 224, end index 256
24.Start index 256, end index 288
24.Start index 288, end index 320
24.Start index 320, end index 352
24.Start index 352, end index 384
24.Start index 384, end index 416
24.Start index 416, end index 448
24.Start index 448, end index 480
24. Loss = 0.007939435541629791
25.Start index 0, end index 32
25.Start index 32, end index 64
25.Start index 64, end index 96
25.Start index 96, end index 128
25.Start index 128, end index 160
25.Start index 160, end index 192
25.Start index 192, end index 224
25.Start index 224, end index 256
25.Start index 256, end index 288
25.Start index 288, end index 320
25.Start index 320, end index 352
25.Start index 352, end index 384
25.Start index 384, end index 416
25.Start index 416, end index 448
25.Start index 448, end index 480
25. Loss = 0.00763771403580904

In [58]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5654047131538391

In [59]:
y_pred.shape

torch.Size([114, 1])

In [60]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.9548611044883728

In [61]:
accuracy_list

[0.96875, 0.96875, 0.9375, 0.9444444179534912]

In [62]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [64]:
from torchinfo import summary
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================